name: Release
on:
  push:
    branches: [main]

jobs:
  build-binary:
    name: haskell-release-macos
    runs-on: macos-latest
    steps:
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: 9.8.2
          cabal-version: 3.10.1.0

      - name: update cabal index
        run: |
          cabal v2-update -v

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build binary
        run: |
          mkdir dist
          cabal v2-install exe:hello --install-method=copy --overwrite-policy=always --installdir=dist

      - name: Set binary path
        uses: allenevans/set-env@v3.0.0
        with:
          BINARY_PATH: ./dist/hello

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello
          path: ${{ env.BINARY_PATH }}
          retention-days: 3


  release:
    needs: [build-binary]
    runs-on: ubuntu-latest
    name: Create Release
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Download Macos x86
        uses: actions/download-artifact@v4
        with:
          name: hello
          path: artifacts/hadolint-Darwin-x86_64

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
        files: hello
