name: Release
on:
  push:
    branches: [main]

jobs:
  build-binary:
    name: haskell-release-macos
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        name: Setup Haskell
        with:
          ghc-version: 9.6.5
          cabal-version: 3.10.1.0

      - uses: actions/cache@v4
        name: Cache ~/.cabal/store
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}

      - name: update cabal index
        run: |
          cabal v2-update -v

      - name: Freeze
        run: cabal freeze

      - name: Build binary
        run: |
          mkdir dist
          cabal v2-install exe:hello --install-method=copy --overwrite-policy=always --installdir=dist

      - name: Set binary path
        uses: allenevans/set-env@v3.0.0
        with:
          BINARY_PATH: ./dist/hello

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello
          path: ${{ env.BINARY_PATH }}
          retention-days: 3


  release:
    needs: [build-binary]
    runs-on: ubuntu-latest
    name: Create Release
    steps:

      - name: Check out
        uses: actions/checkout@v4

      - name: Generate tag
        run: |
          echo "RELEASE_TAG=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV

      - name: Download binary for Macos x86_64
        uses: actions/download-artifact@v4
        with:
          name: hello
          path: artifacts/hello

      - name: Rename
        run: |
          ls -al
          mv artifacts/hello hello
          ls -al

      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: |
            hello
